# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener:
    enabled: true
    default_format: "json"
  body_converter:
    enabled: true
    validate: true
  param_fetcher_listener: true
