# Docker configuration from here: https://dev.to/martinpham/symfony-5-development-with-docker-4hj8
version: '3'

services:
  database:
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - feature-flags-db-data:/var/lib/mysql

  php-fpm:
    container_name: feature-flags_php_fpm_1
    volumes:
      - feature-flags-www:/var/www

  nginx:
    volumes:
      - feature-flags-www:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
volumes:
  feature-flags-www:
  feature-flags-db-data: