# https://github.com/marketplace/actions/add-pr-comment
name: Pull request comments
on:
  pull_request:

jobs:
  pull_request_comments:
    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
        id: extract_branch
      - name: Print branch name
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.branch }}
      - name: Add test coverage report comment
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            Test coverage report: [http://files.antonshell.me/github-actions/feature-flags/${{ steps.extract_branch.outputs.branch }}/coverage/coverage](http://files.antonshell.me/github-actions/feature-flags/${{ steps.extract_branch.outputs.branch }}/coverage/coverage)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default



