# Based on this workflow: https://github.com/Legion2/open-cue-service/blob/main/.github/workflows/pages.yml
name: Swagger UI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: public/swagger-ui
          spec-file: swagger/openapi.yaml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/swagger-ui
